### ISSUE TITLE
MuiInput inside a MuiDialog

### ISSUE THREAD

**Issue by jpablo** [chandu0101/scalajs-react-components#7]
I'm trying to show an input field inside a dialog, like so:

``` scala
    def dialog($: ComponentScopeU[Props, _, Backend]) = {
        val dialogActions = List(
            MuiDialog.Action( text = "CANCEL"),
            MuiDialog.Action( text = "SUBMIT" , onClick = $.backend.onSubmit)
        )

        MuiDialog(ref = theDialogRef,title = "Document name", actions = dialogActions)(
            MuiInput(placeholder = "First name", description = "your first name as DOB", name = "firstname")
        )
    }
```

but it doesn't compile:

```
...
Stack trace suppressed: run last exampleClient/compile:compile for the full output.
[error] (exampleClient/compile:compile) java.lang.IllegalArgumentException: requirement failed: <error>$f is not a valid identifier
```

Am I doing something wrong here?

**Comment by chandu0101** [comment]
strange ! ,try adding empty string as another child (ugly workaround ) until we find root cause

``` scala
 MuiDialog(ref = theDialogRef,title = "Document name", actions = dialogActions)(
            "",
            MuiInput(placeholder = "First name", description = "your first name as DOB", name = "firstname")
        )
```

@sjrd  do you see anything suspicious here .. 

``` scala
java.lang.IllegalArgumentException: requirement failed: <error>$f is not a valid identifier
        at scala.Predef$.require(Predef.scala:219)
        at org.scalajs.core.ir.Trees$.requireValidIdent(Trees.scala:61)
        at org.scalajs.core.ir.Trees$Ident.<init>(Trees.scala:45)
        at org.scalajs.core.compiler.JSEncoding$class.encodeFieldSym(JSEncoding.scala:110)
        at org.scalajs.core.compiler.GenJSCode.encodeFieldSym(GenJSCode.scala:31)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1030)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:930)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:959)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStat(GenJSCode.scala:911)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$42.apply(GenJSCode.scala:1983)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$42.apply(GenJSCode.scala:1983)
        at scala.collection.immutable.List.map(List.scala:277)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genBlock(GenJSCode.scala:1983)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1075)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:930)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$tryGenRepeatedParamAsJSArray$1.apply(GenJSCode.scala:3406)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$tryGenRepeatedParamAsJSArray$1.apply(GenJSCode.scala:3406)
        at scala.collection.immutable.List.map(List.scala:273)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$tryGenRepeatedParamAsJSArray(GenJSCode.scala:3406)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genActualArgs$3.apply(GenJSCode.scala:3268)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genActualArgs$3.apply(GenJSCode.scala:3266)
        at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genActualArgs(GenJSCode.scala:3266)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genNormalApply(GenJSCode.scala:1662)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:1377)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1002)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:930)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApplyTypeApply(GenJSCode.scala:1402)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:1353)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1002)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:930)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:959)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStat(GenJSCode.scala:911)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$42.apply(GenJSCode.scala:1983)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$42.apply(GenJSCode.scala:1983)
        at scala.collection.immutable.List.map(List.scala:277)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genBlock(GenJSCode.scala:1983)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1075)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:930)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genActualArgs$3.apply(GenJSCode.scala:3274)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genActualArgs$3.apply(GenJSCode.scala:3266)
        at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genActualArgs(GenJSCode.scala:3266)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genNormalApply(GenJSCode.scala:1662)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:1377)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1002)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:930)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$tryGenRepeatedParamAsJSArray$1.apply(GenJSCode.scala:3406)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$tryGenRepeatedParamAsJSArray$1.apply(GenJSCode.scala:3406)
        at scala.collection.immutable.List.map(List.scala:277)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$tryGenRepeatedParamAsJSArray(GenJSCode.scala:3406)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genActualArgs$3.apply(GenJSCode.scala:3268)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genActualArgs$3.apply(GenJSCode.scala:3266)
        at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genActualArgs(GenJSCode.scala:3266)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genNormalApply(GenJSCode.scala:1662)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:1377)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1002)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:930)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genActualArgs$3.apply(GenJSCode.scala:3274)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genActualArgs$3.apply(GenJSCode.scala:3266)
        at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genActualArgs(GenJSCode.scala:3266)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genNormalApply(GenJSCode.scala:1662)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:1377)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1002)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genBlock(GenJSCode.scala:1984)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1075)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:930)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMethodDef(GenJSCode.scala:901)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$7$$anonfun$apply$9.apply(GenJSCode.scala:639)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$7$$anonfun$apply$9.apply(GenJSCode.scala:610)
        at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$7.apply(GenJSCode.scala:610)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$7.apply(GenJSCode.scala:571)
        at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMethodWithInfoBuilder(GenJSCode.scala:571)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMethod$1.apply(GenJSCode.scala:532)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMethod$1.apply(GenJSCode.scala:532)
        at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
        at org.scalajs.core.compiler.JSEncoding$class.withNewLocalNameScope(JSEncoding.scala:54)
        at org.scalajs.core.compiler.GenJSCode.withNewLocalNameScope(GenJSCode.scala:31)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMethod(GenJSCode.scala:531)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1(GenJSCode.scala:337)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1$1.apply(GenJSCode.scala:322)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1$1.apply(GenJSCode.scala:322)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1(GenJSCode.scala:322)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genClass(GenJSCode.scala:349)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1$$anonfun$apply$2.apply(GenJSCode.scala:252)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1$$anonfun$apply$2.apply(GenJSCode.scala:242)
        at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1.apply(GenJSCode.scala:242)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1.apply(GenJSCode.scala:224)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.apply(GenJSCode.scala:224)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:441)
        at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:432)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:399)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:399)
        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:399)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.run(GenJSCode.scala:163)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1500)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1580)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
        at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:97)
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
        at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:162)
        at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:96)
        at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:139)
        at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:38)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:36)
        at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:39)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
        at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:66)
        at sbt.inc.Incremental$.compile(Incremental.scala:38)
        at sbt.inc.IncrementalCompile$.apply(Compile.scala:26)
        at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:153)
        at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
        at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
        at sbt.Compiler$.apply(Compiler.scala:74)
        at sbt.Compiler$.apply(Compiler.scala:65)
        at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:789)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (demo/compile:compile) java.lang.IllegalArgumentException: requirement failed: <error>$f is not a valid identifier
[error] Total time: 10 s, completed Apr 4, 2015 4:10:00 PM
[debug] > shell
```

**Comment by sjrd** [comment]
Looks like a compiler bug. Either scalac (trickling down to Scala.js) or Scala.js itself. Could you provide a self-contained reproduction, please?

**Comment by chandu0101** [comment]
sure , check here https://github.com/chandu0101/scalajs-error-reproducible

**Comment by sjrd** [comment]
OK, I will look at it at the end of the week.
