### ISSUE TITLE
NoSuchMethodError thrown during macro expansion

### ISSUE THREAD

**Issue by oswaldo** [chandu0101/scalajs-react-components#72]
Hello,

I was doing an experiment with scalajs-react-components, but as using material-ui is not that straight forward I wanted to run the demo locally to see the webpack piece in action, but I'm finding the following issue:

```
[error] /home/oswaldo/git/scalajs-react-components/core/src/main/scala/chandu0101/scalajs/react/components/materialui/MuiLinearProgress.scala:32: exception during macro expansion: 
[error] java.lang.NoSuchMethodError: scala.reflect.api.Internals$ReificationSupportApi.SyntacticEmptyTypeTree()Lscala/reflect/api/Internals$Reifi$$$$911bdb98bf19646f65c8f8f3866fd1b$$$$peTreeExtractor;
[error]     at chandu0101.macros.tojs.JSMacro$$anonfun$4.apply(JSMacro.scala:88)
[error]     at chandu0101.macros.tojs.JSMacro$$anonfun$4.apply(JSMacro.scala:82)
[error]     at scala.collection.immutable.List.map(List.scala:273)
[error]     at chandu0101.macros.tojs.JSMacro$.applyImpl(JSMacro.scala:81)
[error]     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[error]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:498)
[error]     at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers$$anonfun$resolveJavaReflectionRuntime$2.apply(JavaReflectionRuntimes.scala:34)
[error]     at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers$$anonfun$resolveJavaReflectionRuntime$2.apply(JavaReflectionRuntimes.scala:22)
[error]     at scala.tools.nsc.typechecker.Macros$class.macroExpandWithRuntime(Macros.scala:756)
[error]     val props = JSMacro[MuiLinearProgress](this)

```

The error block apparently repeats for every componnent. Any idea?

**Comment by oyvindberg** [comment]
Did you figure this out @oswaldo ? Was this using the master branch of this project? Based on the error message i would have guessed binary incompatibility issues - that is dependencies on classpath compiled for/by wrong scala version?
